# ruleid: dotfiles.brewfile.no-cargo-installed-tools
brew "dprint"

# ruleid: dotfiles.brewfile.no-cargo-installed-tools
brew "just"

# ruleid: dotfiles.brewfile.no-cargo-installed-tools
brew "rumdl"

# ruleid: dotfiles.brewfile.no-cargo-installed-tools
brew "cargo-update"

# ruleid: dotfiles.brewfile.no-cargo-installed-tools
brew "zizmor"

# ok: dotfiles.brewfile.no-cargo-installed-tools
brew "uv"
